// Generated by CoffeeScript 1.4.0
(function() {
  var coffee;

  coffee = function(message) {
    var answer;
    if (message == null) {
      message = "Ready for some Coffee?";
    }
    answer = confirm(message);
    return "Your answer is " + answer;
  };

}).call(this);
